steps:
  - name: "gcr.io/cloud-builders/git"
    args:
      - "clone"
      - "https://github.com/gclouduniverse/caip-notebooks-marketplace.git"
  - name: "gcr.io/cloud-builders/git"
    dir: "caip-notebooks-marketplace"
    args:
      - "checkout"
      - "${COMMIT_SHA}"
  - name: "gcr.io/caip-notebooks-marketplace-dev/firebase-cli"
    dir: "caip-notebooks-marketplace"
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - |
        FIREBASE_TOKEN="$(gcloud auth application-default print-access-token)" && \
        firebase use dev
  - name: "gcr.io/cloud-builders/gcloud"
    dir: "caip-notebooks-marketplace"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud beta secrets versions access "latest" \
            --secret "firebase-config" \
            --project "caip-notebooks-marketplace-dev" > ./src/common/constants/keys.ts
  - name: "gcr.io/caip-notebooks-marketplace-dev/firebase-cli"
    dir: "caip-notebooks-marketplace"
    entrypoint: "bash"
    args:
      - "-c"
      - "npm run build"
  - name: "gcr.io/caip-notebooks-marketplace-dev/firebase-cli"
    dir: "caip-notebooks-marketplace"
    entrypoint: "bash"
    args:
      - "-c"
      - "firebase deploy"
