steps:
  - name: "gcr.io/caip-notebooks-marketplace-dev/firebase-cli/firebase-cli"
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - "firebase use dev"
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud beta secrets versions access "latest" \
            --secret "firebase-config" \
            --project "caip-notebooks-marketplace-dev" > ./src/common/constants/keys.ts
  - name: "gcr.io/caip-notebooks-marketplace-dev/firebase-cli"
    entrypoint: "bash"
    args:
      - "-c"
      - "npm run build"
  - name: "gcr.io/caip-notebooks-marketplace-dev/firebase-cli"
    entrypoint: "bash"
    args:
      - "-c"
      - "firebase deploy"
